#type: args

train:
  epochs: 10
  batch_size: 1  # 保持最小batch size
  lr: 3.0e-4
  itr_per_epoch: 1.0e+8

diffusion:
  layers: 1  # 进一步减少到1层
  channels: 16  # 进一步减少到16
  nheads: 2  # 减少到2个注意力头
  diffusion_embedding_dim: 32  # 进一步减少到32
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 10  # 大幅减少到10步
  schedule: "quad"
  is_linear: True
  ref_size: 96
  h_size: 168

model:
  is_unconditional: 0
  timeemb: 32  # 进一步减少到32
  featureemb: 8  # 进一步减少到8
  target_strategy: "test"
  num_sample_features: 16  # 进一步减少到16
  use_reference: True 